add data

In [1]:
import tensorflow as tf
import numpy as np

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=4000)

word_index = tf.keras.datasets.imdb.get_word_index()
index2word = dict((i + 3, word) for (word, i) in word_index.items())
index2word[0] = '[pad]'
index2word[1] = '[bos]'
index2word[2] = '[oov]'
x_train = np.array([' '.join([index2word[idx] for idx in text]) for text in x_train])
x_test = np.array([' '.join([index2word[idx] for idx in text]) for text in x_test])

1654784/1641221 [==============================] - 0s 0us/step


In [2]:
vocabulary = list()
for text in x_train:
  tokens = text.split()
  vocabulary.extend(tokens)

vocabulary = set(vocabulary)
print(len(vocabulary))

3998


In [4]:
from tqdm import tqdm

x_train_binary = list()
x_test_binary = list()

for text in tqdm(x_train):
  tokens = text.split()
  binary_vector = list()
  for vocab_token in vocabulary:
    if vocab_token in tokens:
      binary_vector.append(1)
    else:
      binary_vector.append(0)
  x_train_binary.append(binary_vector)

x_train_binary = np.array(x_train_binary)

for text in tqdm(x_test):
  tokens = text.split()
  binary_vector = list()
  for vocab_token in vocabulary:
    if vocab_token in tokens:
      binary_vector.append(1)
    else:
      binary_vector.append(0)
  x_test_binary.append(binary_vector)

x_test_binary = np.array(x_test_binary)

100%|██████████| 25000/25000 [06:59<00:00, 59.61it/s]


In [5]:
my_x_train_binary = x_train_binary
my_y_train = y_train

In [6]:
print("len(my_x_train_binary): ", len(my_x_train_binary))
print("my_x_train_binary:", my_x_train_binary)

len(my_x_train_binary):  25000
my_x_train_binary: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print(type(x_train_binary))
print(len(x_train_binary))
print(x_train_binary)
new_x_train_binary = x_train_binary
np.random.shuffle(new_x_train_binary)
print(len(new_x_train_binary))
print(new_x_train_binary)

Shuffle be like(enna kamei j to x_train_binary j to y_train opos prepei)

In [ ]:
xar = np.array([[1, 11, 111], [2, 22, 222], [3, 33, 333], [4, 44, 444], [5, 55, 555]])
yar = np.array([1, 2, 3, 4, 5])
print(xar)
print(yar)
from sklearn.utils import shuffle
xar, yar = shuffle(xar, yar, random_state=0)
print(xar)
print(yar)

[[  1  11 111]
 [  2  22 222]
 [  3  33 333]
 [  4  44 444]
 [  5  55 555]]
[1 2 3 4 5]
[[  3  33 333]
 [  1  11 111]
 [  2  22 222]
 [  4  44 444]
 [  5  55 555]]
[3 1 2 4 5]


return the position of a word

In [7]:
print(len(vocabulary))
print(vocabulary)

3998
{'taylor', 'brando', 'we', 'victoria', 'alan', 'acted', 'examples', 'degree', 'shallow', 'biggest', 'discovered', 'vietnam', 'halfway', 'essentially', 'trash', 'nation', 'strictly', 'older', 'ghost', 'cheesy', 'country', 'cartoons', 'driven', 'cusack', 'anthony', 'eye', 'treated', 'lake', 'reviewer', 'ripped', 'fancy', 'recognized', 'stick', 'anna', 'stiff', 'split', 'getting', 'morality', 'francisco', 'stanwyck', 'audience', 'quite', 'pregnant', "here's", 'thinking', 'morning', 'changed', 'happening', 'smith', 'concerns', 'asian', 'medical', 'eva', 'terrifying', 'wall', 'insulting', 'footage', 'driver', 'work', 'rating', 'sacrifice', 'status', "there's", 'builds', 'irritating', "we've", 'shown', 'arnold', 'cried', 'nick', 'instantly', 'progress', 'sharp', 'references', 'leaving', "i'd", 'their', 'ho', 'joy', 'failure', 'checking', 'desperate', 'christian', 'remotely', 'typical', 'surprised', 'technical', 'eddie', 'bought', 'twelve', 'on', 'lots', 'stupid', 'asked', 'nature', 'gen

ID3 class

In [ ]:
class ID3:
    def __init__(self, x_tr_bin:list(), y_tr:list(), wor:list()):
        self.x_tr_bin = x_tr_bin
        self.y_tr = y_tr
        self.wor  = wor

    def run(self):
      j = 0 #next = findTheNextWord(max, words, c)
      good_result = 0
      print('------------------------------stolou------- len(self.x_tr_bin)', len(self.x_tr_bin))
      print("------------------------------stolou------- hello let's start")
      print(self.wor)
      for sentense in self.x_tr_bin:
        print('!!@@@@!!@!@!@protash')
        copy_words = self.wor.copy()
        max = copy_words.pop()
        stopTheWhile = False
        while len(copy_words) !=0 and not stopTheWhile:
          c = findValueFromArray(sentense, max.index)
          while len(copy_words) != 0 and max.p0 != 1 and max.p1 !=1:
            next = findTheNextWord(max, copy_words, c)
            if(next == None):
              stopTheWhile = True
              break
            max = next
        if(max.p0 > max.p1):
          if 0 == self.y_tr[j]:
            good_result += 1
        else:
          if 1 == self.y_tr[j]:
            good_result += 1

        j+=1
        
        print('------------------------------stolou------- ', good_result/j*100)
      return good_result/j*100

Run ID3 class

In [ ]:
id3Obj = ID3(x_train_binary, y_train, words)
id3Obj.run()

RF pou paizw panw tou

In [113]:
import random
from random import randint
from sklearn.utils import shuffle
from sklearn.tree import DecisionTreeClassifier


# @TODO def myRF(x_train, y_train, words, numOfTrees):
def myRF(x_train, y_train, numOfTrees):
  # random size for words' subset(prepei na einai idio gia kathe dentro)
  # @TODO wordsSize = 100 # randint(100, len(words))

  randomForest = []
  # @ del newX_train = x_train[:5] # prosorina, meta enna mpei oullh alios osh theloume
  # @ del newY_train = y_train[:5] # >>

  for i in range(numOfTrees):
    # @TODO subWords = random.choices(words, k=5) # subWords = random.choices(words, k=wordsSize)
    # @TODO shuffle() j to subWords
    # @TODO randomForest.append(ID3(newX_train, newY_train, subWords))
    # me etoimo ID3:
    dt = DecisionTreeClassifier(criterion='entropy')
    x_train, y_train = shuffle(x_train, y_train)
    dt.fit(x_train, y_train)
    temp = dt.predict(x_train)
    randomForest.append(temp) # @TODO (enna kamnw to idio prama, enna vallw mes ton randomForest[] ton pinaka pou enna epistrefei o apostolou)

  for pin in randomForest:
    print(pin)

  telikosPinakas = predictRF(randomForest)

  return telikosPinakas

  # @ del print("len(randomForest): ", len(randomForest))


  # @TODO for obj in randomForest:
    # @TODO temp = obj.run()
    # @TODO resRF.append(temp)
    # print('end of tree\n\n\n\n', temp)


In [115]:
myRF(x_train_binary, y_train, 2)
print(x_train_binary)
print(len(x_train_binary))
#print(y_train)

[0 1 1 ... 0 0 1]
[1 1 0 ... 1 1 0]
25000
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
25000


In [124]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

print(classification_report(y_test, myRF(x_test_binary, y_test, 8)))

[1 0 1 ... 0 0 0]
[1 1 1 ... 1 1 1]
[1 1 0 ... 0 1 1]
[0 1 1 ... 0 0 0]
[0 1 0 ... 1 1 0]
[0 0 1 ... 1 0 1]
[0 1 0 ... 1 0 1]
[1 0 0 ... 1 1 1]
25000
              precision    recall  f1-score   support

           0       0.50      0.64      0.56     12500
           1       0.50      0.37      0.42     12500

    accuracy                           0.50     25000
   macro avg       0.50      0.50      0.49     25000
weighted avg       0.50      0.50      0.49     25000



assoi j midenika kathe stilis

In [68]:
arr_2ad = np.array([[1, 1, 0],
                   [2, 1, 2],
                   [2, 1, 0]])

# vazontas arr_2d == myNum, metra posa myNum eshei h kathe stili
n_zeros = np.count_nonzero(arr_2ad==1, axis=0)
# display the count of zeros
print(n_zeros)

[1 3 0]


In [92]:
testRF = [[1, 0, 0, 1, 1, 0], [1, 0, 1, 0, 1, 1], [1, 0, 0, 1, 1, 0]]

testRFnp = np.array(testRF)
midenika = np.count_nonzero(testRFnp==0, axis=0)
assoi = np.count_nonzero(testRFnp==1, axis=0)

toReturn = list()

for i in range(len(testRFnp[0])):
  if midenika[i] > assoi[i]:
    toReturn.append(0)
  elif assoi[i] > midenika[i]:
    toReturn.append(1)
  elif assoi[i] == midenika[i]:
    toReturn.append(0)

print(toReturn)
print(len(testRFnp))

[1, 0, 0, 1, 1, 0]
3


In [107]:
def predictRF(array_2d):
  np_2d_array = np.array(array_2d)
  
  midenika = np.count_nonzero(np_2d_array==0, axis=0)
  assoi = np.count_nonzero(np_2d_array==1, axis=0)

  toReturn = list()
  print(len(np_2d_array[0]))
  for i in range(len(np_2d_array[0])):
    if midenika[i] > assoi[i]:
      toReturn.append(0)
    elif assoi[i] > midenika[i]:
      toReturn.append(1)
    elif assoi[i] == midenika[i]:
      toReturn.append(0)
    
  return toReturn

In [108]:
testRF = [[1, 0, 0, 1, 1, 0], [1, 0, 1, 0, 1, 1], [1, 0, 0, 1, 1, 0]]
print(predictRF(testRF))

6
[1, 0, 0, 1, 1, 0]


Etimos ID3 me: telefteioPinaka = predict()

In [43]:
from sklearn.tree import DecisionTreeClassifier

original_x_train_binary = x_train_binary
original_y_train = y_train

dt = DecisionTreeClassifier(criterion='entropy')
dt.fit(x_train_binary, y_train)

telikosPinakasID3 = dt.predict(x_train_binary)

print("TIPOS: ", type(telikosPinakasID3))

print("telikosPinakasID3:\n")
print(telikosPinakasID3)
print("len(telikosPinakasID3)")
print(len(telikosPinakasID3))

TIPOS:  <class 'numpy.ndarray'>
telikosPinakasID3:

[0 0 0 ... 0 0 0]
len(telikosPinakasID3)
25000


In [28]:
# print(telikosPinakasID3)
telikosT = telikosPinakasID3
for i in range(len(telikosT)):
  if telikosT[i] == 0:
    telikosT[i] = 1
  if telikosT[i] == 1:
    telikosT[i] = 0

print(len(telikosT))
print(telikosT)

25000
[0 0 0 ... 0 0 0]


shuffle() tous pinakes mas(x_train_bin j y_train)

In [ ]:
import random
from random import randint
import tensorflow as tf
import numpy as np
from sklearn.utils import shuffle

# ekso apo th methodo RF
x_train_binary_original = x_train_binary # x_array = np.array([[1, 11, 111], [2, 22, 222], [3, 33, 333], [4, 44, 444], [5, 55, 555]])
y_train_original = y_train # y_array = np.array([1, 2, 3, 4, 5])

# mesa sth methodo tou RF(for loop pou tha gemizi ton pinaka):
x_train_binary, y_train = shuffle(x_train_binary, y_train)
print("x_train_binary: ", x_train_binary)
print("y_train: ", y_train)

ORIGINAL RF PRIN NA KAMW ALLAGES:

In [ ]:
import random
from random import randint
"""
- emina sth fash pou enna mikratw thn lista words(tixeo iposinolo, idio gia oulla)
na dw dld pws enna gnt o xorismos giati en j h lista words pou enna allassei gia kathe dentro
na eshei omos diplotipa
"""
#print(len(words))
#print(words)

numOfTrees = 3 # number of trees in random forest, kanonika prepei na en tosa nmz: int(len(x_train_binary) * 0.3)

# random size for words' subset(prepei na einai idio gia kathe dentro)
wordsSize = 100 # randint(100, len(words))
newl = random.choices(words, k=wordsSize) # subets with same length
#print(len(newl))

"""
id3Obj = ID3(x_train_binary, y_train, words)
"""
randomForest = []
resRF = []
newX_train_binary = x_train_binary[:5] # prosorina, meta enna mpei oullh alios osh theloume
newY_train = y_train[:5] # >>

for i in range(numOfTrees):
  subWords = random.choices(words, k=5) # subWords = random.choices(words, k=wordsSize)
  randomForest.append(ID3(newX_train_binary, newY_train, subWords))

print(len(randomForest))

for obj in randomForest:
  temp = obj.run()
  resRF.append(temp)
  print('end of tree\n\n\n\n', temp)



print('\nresRF: ', resRF)
